### PR TITLE
0.11.0

### LINKED ISSUE #93: Parsing deeply nested JSON
I'm hitting the stack size limit while parsing deeply nested data from a profiler (e.g. Chrome). Test case to chain ` read_object` and `read_array`:
```rust
#[test]
fn parse_deeply_nested_arrays_and_objects() {
    let depth = 5000; // note: small numbers won't do here.
    let mut text = String::new();
    for _ in 0..depth {
        text.push_str("[{\"a\":");
    }
    text.push_str("null");
    for _ in 0..depth {
        text.push_str("}]");
    }

    let data = parse(&text);

    assert!(!data.is_err());
}
```
This could be tricky to fix due to the LL(*) parsing strategy.

### PR DESCRIPTION
**Pull request by maciejhirsz**
Fixes #93

### CODE REVIEW

**Comment by dtolnay** [comment]
Isn't this a breaking change? If someone does a match on `Error` this breaks their code.

**Comment by maciejhirsz** [comment]
Good point.

**Comment by Mark-Simulacrum** [comment]
While we're making a breaking change, maybe update the Error enum to have a `__Nonexhaustive` variant to allow future extensibility?

**Comment by maciejhirsz** [comment]
@Mark-Simulacrum is this an advised best practice?

I think while this library is still in pre-1.0 state the occasional breaking change of this (microscopic) magnitude is quite okay, and post 1.0 I'd rather want to have the Error types set and solid.

**Comment by Mark-Simulacrum** [comment]
I know this is used in the stdlib, for example, so I'd say that yes--any enums that may gain new variants can/should have a variant marked for this purpose.

**Comment by meh** [comment]
@Mark-Simulacrum that's only for enums that you **NEVER** want to be fully exhausted, i.e. to always have a catch-all at the end, not for preventing breaking changes.

**Comment by Mark-Simulacrum** [comment]
@meh That's true. Though, to some extent, there is a relationship between the two--if it's never fully exhausted, then there's not going to be breaking changes when adding new variants.

**Comment by maciejhirsz** [comment]
I'll leave the Error enum as is then, don't really want to add "unknown error" to printing traits either.

**Pull request merged**
